### ISSUE TITLE
UAX #29 Sentence Boundaries

### ISSUE THREAD

**Issue by peakji** [akahuku/unistring#1]
Hey @akahuku, thanks for making this awesome library!

Any plan of implementing the [Sentence Boundaries](http://www.unicode.org/reports/tr29/#Sentence_Boundaries) section of UAX #29?

**Comment by akahuku** [comment]
Thanks for the suggestion.
I implemented getSentences().
It passes [all 502 test patterns](http://www.unicode.org/Public/9.0.0/ucd/auxiliary/SentenceBreakTest.txt) provided by Unicode.org.

**Comment by peakji** [comment]
@akahuku 👍👍👍
