### ISSUE TITLE
How to get words without punctuation marks?

### ISSUE THREAD

**Issue by feuerste** [akahuku/unistring#2]
Hi @akahuku thank you for this library. When using `getWords`, is there any way to distinguish punctuation marks (like `.,;()"'`) and white spaces from actual words in the results? The returned type isn't clear to me. Thank you!

**Comment by akahuku** [comment]
`getWords` returns an array of object, which has 'type' property. This indicates the type of first letter of each word. Valid values for type are defined in: 
https://github.com/akahuku/unistring/blob/7250d7631444539636663b9f2a83ba6d292c8cb1/unistring.js#L348-L376
These values correspond to word boundaries defined in http://unicode.org/reports/tr29/#Word_Boundaries and are listed in http://www.unicode.org/Public/9.0.0/ucd/auxiliary/WordBreakProperty.txt

Therefore, if you want to pick up whitespace, for example there is a code like:
```javascript
var result = Unistring.getWords('hello, world');
for (var i = 0; i < result.length; i++) {
  if (result[i].type == Unistring.WBP.Space) {
    // whitespace
  }
}

**Comment by feuerste** [comment]
Ok, thanks a lot!
